### ISSUE TITLE
проблеми з обсягами тексту

### ISSUE THREAD

**Issue by ipiwebtech** [AndPris/Web_Lab1#1]
<img width="952" alt="overtexting" src="https://github.com/AndPris/Web_Lab1/assets/129291207/02ac511d-66b3-4d88-9dfa-92bc5ebe47aa">

всюди текст вилазить за межі своїх блоків, із супутніми артефактами

дозволяйте блокам розтягуватися по вертикалі,
дозволяйте загалом сторінці розтягуватися по вертикалі,
щоб вміщувати обсяги тексту

перевіряйте самостійно, це вказано в одному з пунктів завдання л.р.

**Comment by AndPris** [comment]
виправив
